### ISSUE TITLE
Something Unproper with SearchBarMenu

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/qtsasstheme#2]
Hi, there. Recently I've found that the change between black and light modes cannot be apply to the InstantSearchBar, like this:
![image](https://user-images.githubusercontent.com/97718634/216775698-ebc27da1-c9bd-4ca0-8e29-46a22033fe04.png)
![image](https://user-images.githubusercontent.com/97718634/216774641-2fde8e54-5d62-4fc5-bce5-72c08caa29c2.png)
when inputting something into the LineEdit in dark modes, the texts cannot be seen clearly.
Could you help me with this? I'll really appreciate that.
Looking forward to your reply^^

**Comment by yjg30737** [comment]
Sorry for the belated reply, as always 😫

InstantSearchBar is customized widget which has its own style and its style won't be changed by qtsasstheme.

Even if i changed the source of InstantSearchBar for qtsasstheme, it would be very inefficient.

After all InstantSearchBar's style is based on static css, not sass. So only way to do so is making it controlled by qtsasstheme.

**That being said, i need to import the widgets to qtsasstheme 
or making a completely new repository of qtsasstheme and customized widgets.**

If would not take too long. Only about a week or less than a week.

And of course i'll remove the PyqtResourceHelper and SvgLabel in the InstantSearchBar because that is just completely unnecessary at this point.. I was not good at Python back then. 😔

But if you need hurry and don't care much about style of search bar right now..

```python
from PyQt5.QtWidgets import QWidget, QLineEdit, QGridLayout, QLabel, \
    QHBoxLayout, QApplication
from PyQt5.QtCore import pyqtSignal
from pyqt_resource_helper import PyQtResourceHelper
from pyqt_svg_label import SvgLabel


class InstantSearchBar(QWidget):
    searched = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        # search bar label
        self.__label = QLabel()

        self._initUi()

    def _initUi(self):
        self.__searchLineEdit = QLineEdit()
        self.__searchLineEdit.setPlaceholderText('Search...')
        ps = QApplication.font().pointSize()

        self.__searchBar = QWidget()
        self.__searchBar.setObjectName('searchBar')

        lay = QHBoxLayout()
        lay.addWidget(self.__searchLineEdit)
        self.__searchBar.setLayout(lay)
        lay.setContentsMargins(0, 0, 0, 0)
        lay.setSpacing(0)

        self.__searchLineEdit.setFocus()
        self.__searchLineEdit.textChanged.connect(self.__searched)

        self.setAutoFillBackground(True)

        lay = QHBoxLayout()
        lay.addWidget(self.__searchBar)
        lay.setContentsMargins(0, 0, 0, 0)
        lay.setSpacing(2)

        self._topWidget = QWidget()
        self._topWidget.setLayout(lay)

        lay = QGridLayout()
        lay.addWidget(self._topWidget)

        searchWidget = QWidget()
        searchWidget.setLayout(lay)
        lay.setContentsMargins(0, 0, 0, 0)

        lay = QGridLayout()
        lay.addWidget(searchWidget)
        lay.setContentsMargins(0, 0, 0, 0)

        # self.__setStyle()

        self.setLayout(lay)

    # ex) searchBar.setLabel(True, 'Search Text')
    def setLabel(self, visibility: bool = True, text=None):
        if text:
            self.__label.setText(text)
        self.__label.setVisible(visibility)

    def __setStyle(self):
        self.__searchIconLbl.setSvgFile('ico/search.svg')
        PyQtResourceHelper.setStyleSheet([self.__searchLineEdit, self.__searchBar, self],
                                         ['style/lineedit.css', 'style/search_bar.css', 'style/widget.css'])

    def __searched(self, text):
        self.searched.emit(text)

    def setSearchIcon(self, icon_filename: str):
        self.__searchIconLbl.setIcon(icon_filename)

    def setPlaceHolder(self, text: str):
        self.__searchLineEdit.setPlaceholderText(text)

    def getSearchBar(self):
        return self.__searchLineEdit

    def getSearchLabel(self):
        return self.__searchIconLbl

    def showEvent(self, e):
        self.__searchLineEdit.setFocus()
```

Copy this, and paste it into instantSearchBar.py

This will get rid of style :)

**Comment by Liskelleo** [comment]
That's very nice of you! Also, I have some ideas about the adaption.
We've known that the difference between one of two types of modes (either light or dark) is the parameter `$bgcolor` in `_variables.scss`, like this (a comparation of `dark_grey` and `dark_blue` themes in `var` file):
![无标题](https://user-images.githubusercontent.com/97718634/217268115-a453d1c7-37a8-495d-8730-877f0636f450.png)
Therefore, why not add an optional parameter (e.g., `bgcolor`) in method `setThemeFiles` for users----just like the parameter `fontsize` which was added last time, so that users could have more flexible choices of background colors based on light/dark modes.
Anyway, thanks for helping me so much^^ Btw, I have another question for you via email, so please keep an eye on it.

**Comment by yjg30737** [comment]
You can customize the theme with getThemeFiles  

https://github.com/yjg30737/qtsasstheme#customizing-theme

I've added it(as you mentioned, color) in getThemeFiles, because it needs to convert the sass into css.

setThemeFiles method applies those css files to PyQt widgets.

**But if you really need to do it with only setThemeFiles, i'll do it.**

After all, it should be changed completely dynamically - i know you want to change the theme in runtime. So that feature is needed.

Thanks for inspiring me :)

**Comment by Liskelleo** [comment]
Since that you've added similar parameter in `getThemeFiles` which I didn't pay enough attention to, so that won't be a bother. I've just tested that parameter in `getThemeFiles` can changed the theme dynamically successfully, however I don't know much about the efficiency by doing this way. Relative codes as below:
```
t.getThemeFiles(theme='#ffffff')
t.setThemeFiles(main_window=self)
```
So maybe you don't need to do it with only `setThemeFiles`. Thanks for your help^^

**Comment by yjg30737** [comment]
No problem :)
